### ISSUE TITLE
Consul.AspNetCore NuGet package naming collision issue

### ISSUE THREAD

**Issue by gabor182** [G-Research/consuldotnet#104]
The Consul.AspNetCore nuget package cannot be found on NuGet.org. There's already a package with this name there, but it's not yours, it's been published by zlzforever in 2018. You can find the package here: [Consul.AspNetCore](https://www.nuget.org/packages/Consul.AspNetCore/)

Though I think your CI/CD pipeline tried to publish your package, since you are listed as the owner of the package too. I'm not sure how the nuget.org package repository is configured, I suppose it didn't accept your package due to the name collision, but added you as the owner of the already existing package.

**Comment by mfkl** [comment]
Hi,

Thanks for your concern. We did contact the owner of this package and retrieved ownership, so we can push this package to NuGet. All should be OK, though it appears the latest Consul.AspNetCore release wasn't pushed to NuGet for some reason?

**Comment by gabor182** [comment]
Hi mfkl,

When do you plan to fix this issue? I'd like to use your Consul.AspNetCore package, but since it's not published yet, I had to copy-paste the source code of it into my project.

**Comment by jgiannuzzi** [comment]
Hi @gabor182, we have indeed made all the necessary ownership transfer and CI changes to be able to publish `Consul.AspNetCore` to nuget.org. The reason it hasn't been published yet is that we were waiting to have some changes to `Consul` before creating a new release (the process for publishing is fully automated and auditable in [our CI](https://github.com/G-Research/consuldotnet/actions)).

We have decided to create a new release in the coming days so that our version of `Consul.AspNetCore` will finally get pushed to nuget.org. In the meantime, you can use our [preview version](https://github.com/G-Research/consuldotnet#preview-versions) instead of copy-paste 😄

**Comment by mfkl** [comment]
@gabor182 Try this out https://www.nuget.org/packages/Consul.AspNetCore/1.6.10.2

Closing the issue as this has been clarified :)

**Comment by gabor182** [comment]
Thanks, @mfkl! :)
